import React, { useRef, useState } from 'react';
import { FaCloudUploadAlt, FaFileAlt, FaSpinner } from 'react-icons/fa';

// These match the files in your public/saved_dashboards folder
const PRESETS = [
  { id: 'exec-overview.json.dashboard', label: 'Executive Overview' },
  { id: 'analise-global-zonas.json.dashboard', label: 'Global Zones Analysis' },
  {
    id: 'analise-partidas-estacao.json.dashboard',
    label: 'Station Departures Analysis',
  },
  { id: 'sensores-por-estacao.json.dashboard', label: 'Sensors per Station' },
];

type LoadPopupProps = {
  onCancel: () => void;
  onLoadFile: (file: File) => Promise<void>;
};

export default function LoadPopup({ onCancel, onLoadFile }: LoadPopupProps) {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [loadingId, setLoadingId] = useState<string | null>(null);

  const handlePresetClick = async (filename: string) => {
    setLoadingId(filename);
    try {
      // 1. Get the dynamic base URL generated by Vite
      const baseUrl = import.meta.env.BASE_URL;

      // 2. Prepend it to the fetch request (baseUrl always ends with a '/')
      const response = await fetch(`${baseUrl}saved_dashboards/${filename}`);

      if (!response.ok)
        throw new Error(
          `Failed to fetch dashboard template: ${response.statusText}`,
        );

      const blob = await response.blob();
      // Package it exactly as if the user selected it from their computer
      const file = new File([blob], filename, {
        type: 'application/octet-stream',
      });

      await onLoadFile(file);
    } catch (error) {
      console.error(error);
      alert('Failed to load sample dashboard.');
    } finally {
      setLoadingId(null);
    }
  };

  return (
    <div
      style={{
        width: 400,
        display: 'flex',
        flexDirection: 'column',
        gap: 24,
        padding: '4px 0',
      }}
    >
      {/* 1. Local Upload Section */}
      <div>
        <h4 style={{ margin: '0 0 12px 0', color: '#334155', fontSize: 14 }}>
          Upload from your computer
        </h4>
        <input
          type="file"
          accept=".json,.dashboard,.zip"
          style={{ display: 'none' }}
          ref={fileInputRef}
          onChange={async (e) => {
            const file = e.target.files?.[0];
            if (file) await onLoadFile(file);
          }}
        />
        <button
          onClick={() => fileInputRef.current?.click()}
          style={{
            width: '100%',
            padding: '16px',
            borderRadius: 8,
            border: '2px dashed #cbd5e1',
            background: '#f8fafc',
            cursor: 'pointer',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            gap: 10,
            color: '#475569',
            fontWeight: 600,
            transition: 'all 0.2s',
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.background = '#f1f5f9';
            e.currentTarget.style.borderColor = '#94a3b8';
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.background = '#f8fafc';
            e.currentTarget.style.borderColor = '#cbd5e1';
          }}
        >
          <FaCloudUploadAlt size={22} color="#3b82f6" />
          <span>Browse Files...</span>
        </button>
      </div>

      <div style={{ position: 'relative', textAlign: 'center' }}>
        <div
          style={{
            position: 'absolute',
            top: '50%',
            left: 0,
            right: 0,
            borderTop: '1px solid #e2e8f0',
          }}
        ></div>
        <span
          style={{
            position: 'relative',
            background: '#fff',
            padding: '0 12px',
            color: '#94a3b8',
            fontSize: 12,
            fontWeight: 700,
          }}
        >
          OR CHOOSE A TEMPLATE
        </span>
      </div>

      {/* 2. Sample Dashboards Section */}
      <div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
          {PRESETS.map((preset) => (
            <button
              key={preset.id}
              onClick={() => handlePresetClick(preset.id)}
              disabled={loadingId !== null}
              style={{
                padding: '12px 16px',
                borderRadius: 8,
                border: '1px solid #e2e8f0',
                background: '#fff',
                cursor: loadingId ? 'wait' : 'pointer',
                display: 'flex',
                alignItems: 'center',
                gap: 12,
                textAlign: 'left',
                color: '#334155',
                boxShadow: '0 1px 2px rgba(0,0,0,0.02)',
                transition: 'all 0.2s',
                opacity: loadingId && loadingId !== preset.id ? 0.6 : 1,
              }}
              onMouseEnter={(e) =>
                (e.currentTarget.style.background = '#f8fafc')
              }
              onMouseLeave={(e) => (e.currentTarget.style.background = '#fff')}
            >
              {loadingId === preset.id ? (
                <FaSpinner className="spin" color="#3b82f6" />
              ) : (
                <FaFileAlt color="#94a3b8" />
              )}
              <span style={{ fontWeight: 500, flex: 1 }}>{preset.label}</span>
            </button>
          ))}
        </div>
      </div>

      {/* Cancel Button */}
      <div
        style={{ display: 'flex', justifyContent: 'flex-end', marginTop: 8 }}
      >
        <button
          onClick={onCancel}
          style={{
            padding: '8px 16px',
            borderRadius: 6,
            border: '1px solid #cbd5e1',
            background: '#fff',
            cursor: 'pointer',
            fontWeight: 500,
            color: '#475569',
          }}
        >
          Cancel
        </button>
      </div>

      {/* Inline style for the spinner animation */}
      <style>{`
        @keyframes spin { 100% { transform: rotate(360deg); } }
        .spin { animation: spin 1s linear infinite; }
      `}</style>
    </div>
  );
}
